from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HTML = ROOT / "btc-swing-strategy" / "mecanism.html"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        print(f"[mobile-safe] {label}: already absent")
        return text
    print(f"[mobile-safe] {label}: replaced")
    return text.replace(old, new, 1)


def ensure_mobile_safe_css(text: str) -> str:
    """Keep the public BTC page compact on Android WebView.

    This hides non-essential visual-summary panels that are still generated by
    visual-model-summary.js, without touching the audited signal card or legend.
    """
    start = "/* MOBILE_SAFE_VISUAL_SUMMARY_COMPACT_START */"
    end = "/* MOBILE_SAFE_VISUAL_SUMMARY_COMPACT_END */"
    block = f"""{start}
.cxv-confirm,
.cxv-narrative {{
  display: none !important;
}}
{end}
"""

    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end) + r"\s*", re.S)
    if pattern.search(text):
        print("[mobile-safe] compact visual summary css: refreshed")
        return pattern.sub(block, text, count=1)

    if "</style>" in text:
        print("[mobile-safe] compact visual summary css: inserted")
        return text.replace("</style>", block + "\n</style>", 1)

    print("[mobile-safe] compact visual summary css: no style tag found")
    return text


def main() -> None:
    text = HTML.read_text(encoding="utf-8")
    original = text

    # 1) Remove Plotly from the mobile page. The old chart is no longer a core UI
    # surface, and Plotly is one of the heaviest runtime costs in Android WebView.
    text = re.sub(
        r'\n\s*<script\s+src="https://cdn\.plot\.ly/plotly-[^"]+\.min\.js"></script>\s*',
        "\n",
        text,
        count=1,
    )

    # 2) Stop OHLC/chart polling. Keep the old functions in the file for audit/history,
    # but do not execute them on page boot.
    text = replace_once(text, "      loadOHLC();\n", "      // Mobile-safe: OHLC/Plotly chart disabled.\n", "disable loadOHLC boot call")
    text = replace_once(text, "      setInterval(loadOHLC, 60 * 1000);\n", "      // Mobile-safe: OHLC polling disabled.\n", "disable loadOHLC interval")

    # 4) Clean the daily card markup. The renderer now owns this area and displays
    # only the audited signal card + legend. Remove stale interpretation markup,
    # duplicated toggle ids, and full interpretation placeholders.
    clean_daily_block = '''    <!-- DAILY_COHESIV_INTERPRETATION_CARD_START -->
    <div class="card card-secondary" id="daily-ai-card">
      <div class="card-inner" id="daily-cylinder-root">
        Se încarcă semnalul auditat...
      </div>
    </div>
    <!-- DAILY_COHESIV_INTERPRETATION_CARD_END -->'''

    text, n = re.subn(
        r'    <!-- DAILY_COHESIV_INTERPRETATION_CARD_START -->.*?    <!-- DAILY_COHESIV_INTERPRETATION_CARD_END -->',
        clean_daily_block,
        text,
        count=1,
        flags=re.S,
    )
    print(f"[mobile-safe] daily card: cleaned blocks={n}")

    # Extra compact mode: hide the 7/30 day horizon panel and the two narrative
    # expanders from the visual summary. Signal + legend remain untouched.
    text = ensure_mobile_safe_css(text)

    if text == original:
        print("[mobile-safe] no changes needed")
    else:
        HTML.write_text(text, encoding="utf-8")
        print(f"[mobile-safe] patched {HTML}")


if __name__ == "__main__":
    main()
